name: CI
on:
  schedule:
    - cron: '0 10,18 * * 1-5'
  push:
    branches: ['*']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Validate Packer Image
        uses: dawitnida/packer-github-actions/validate@master
        env:
          TEMPLATE_FILE_NAME: marketplace-image.json
          DIGITALOCEAN_TOKEN: ${{ secrets.digitalocean_token }}
